version: '3.8'

services:
  database:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: fastapi_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aswin2000
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"
